export const MochaHandleKey = {
  GET_DIRECTORY_TREE: 'GET_DIRECTORY_TREE',
  GET_DIRECTORY_TREE_WITH_PARENT: 'GET_DIRECTORY_TREE_WITH_PARENT',
  OPEN_DIALOG: 'OPEN_DIALOG',

  WINDOW_MINIMIZE: 'WINDOW_MINIMIZE',
  WINDOW_TOGGLE_MAXIMIZE: 'WINDOW_TOGGLE_MAXIMIZE',
  WINDOW_CLOSE: 'WINDOW_CLOSE',
};
