export const MochaHandleKey = {
  GET_DIRECTORY_TREE: 'GET_DIRECTORY_TREE',
  GET_DIRECTORY_TREE_WITH_PARENT: 'GET_DIRECTORY_TREE_WITH_PARENT',
  OPEN_DIALOG: 'OPEN_DIALOG',
  READ_FILE: 'READ_FILE',
  WRITE_FILE: 'WRITE_FILE',
  EXIST_FILE: 'EXIST_FILE',
  DELETE_FILE: 'DELETE_FILE',

  WINDOW_MINIMIZE: 'WINDOW_MINIMIZE',
  WINDOW_TOGGLE_MAXIMIZE: 'WINDOW_TOGGLE_MAXIMIZE',
  WINDOW_CLOSE: 'WINDOW_CLOSE',
};
